### ISSUE TITLE
Gorm support

### ISSUE THREAD

**Issue by zasran** [SAP/go-hdb#1]
This is not a strictly go-hdb issue, not sure how else to reach go-hdb developers though. Feel free to close as invalid.

Any thoughts on Gorm https://github.com/jinzhu/gorm support? It seems that all that would be needed is implementation of Dialect interface in Gorm (not here, that's why this issue is not strictly go-hdb issue). As far as I can tell Gorm is one of the better, maybe best, ORM for Go.

Note: also created issue https://github.com/jinzhu/gorm/issues/615 in Gorm issue tracker where it's appropriate but you'd never see it.

**Comment by d024441** [comment]
Thanks for the information - actually there is no plan to contribute to any of the Golang ORMs. Nonetheless, the needed information to add a 'Dialect interface' implementation is public available at [HANA SQL reference](http://help.sap.com/hana/sap_hana_sql_and_system_views_reference_en.pdf).

**Comment by zasran** [comment]
Ok, thanks for the response!
