### ISSUE TITLE
help with decimals

### ISSUE THREAD

**Issue by scotthathaway** [SAP/go-hdb#10]
I am trying to use the go driver to get decimals out of Hana.  Can you please give me an example of pulling a decimal field and then converting it so that it shows up as the decimal value?  I am seriously confused since I am new to Go.  I can pull other datatypes without issue, but decimals come in all screwed up with strange unicode looking codes that say they are not valid unicode.

When I pull the data:

If the field type is decimal: ACWP_HRS_EXCESS_RUNTIME:"\ufffd\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u000080"

If the field type is double:
DBL_ACWP_HRS_EXCESS_RUNTIME: 6.392

How do I get the decimal to show 6.392 as well?

Thanks,
Scott

**Comment by d024441** [comment]
Hi,
for decimals please use type Decimal (or NullDecimal respectively). Decimal is a Go big.Rat type (which provides you with methods to convert it to a string, etc.) extended by Scan and Value methods to use it in conjunction with the Go SQL interface.
Please see
- https://godoc.org/github.com/SAP/go-hdb/driver#Decimal for documentation and
- https://github.com/SAP/go-hdb/blob/master/driver/datatype_test.go for usage

Please give me feedback if that helps or if you need some example code in addition.

**Comment by scotthathaway** [comment]
I saw the example, but did not know how to actually implement it since I am new to Go.

Here is my code:

`	rows, err := db.Query("select top 1 my_dec_field from system.mytable")
	if err != nil {
		return "", err
	}
	defer rows.Close()
	columns, err := rows.Columns()
	if err != nil {
		return "", err
	}
	count := len(columns)
	tableData := make([]map[string]interface{}, 0)
	values := make([]interface{}, count)
	valuePtrs := make([]interface{}, count)
	for rows.Next() {
		for i := 0; i < count; i++ {
			valuePtrs[i] = &values[i]
		}
		rows.Scan(valuePtrs...)
		entry := make(map[string]interface{})
		for i, col := range columns {
			var v interface{}
			val := values[i]
			b, ok := val.([]byte)
			if ok {
				v = string(b)
			} else {
				v = val
			}
			entry[col] = v
		}
		tableData = append(tableData, entry)
	}`

Given this code, how would I tell that the field that came out was a decimal and then decode it?

Thanks,
Scott

**Comment by d024441** [comment]
Hi,
the driver uses type Rat from math.big to represent database decimals in Go. For the conversion between the database decimal representation and the Go Rat type, the driver implements the Decimal data type.
For the usage please see the newly added example at:
https://godoc.org/github.com/SAP/go-hdb/driver#example-Decimal
Hope, that helps.

**Comment by iambudi** [comment]
@d024441 The sample usage does not clear since it does not use precision or comma. Let's say i have populated data in table `1550000.22`. Using the example it will be read as `155000022`.

```go
var out driver.Decimal
fmt.Printf("Decimal value: %s", (*big.Rat)(&amount).String()) // Cast scan variable to *big.Rat to use *big.Rat methods.
```

**Comment by iambudi** [comment]
Should i open a new issue? Thanks

**Comment by d024441** [comment]
Yes, sure - and please provide a complete example - in the example shared the definition and value of amount is not clear.
