### ISSUE TITLE
comments at the beginning of the query throws error

### ISSUE THREAD

**Issue by yesoreyeram** [SAP/go-hdb#104]
When adding comments at the beginning of the query, it throws error with the hana driver. While adding the comments at the end works fine

```
HANA Driver version :github.com/SAP/go-hdb v0.111.7
```

Minimal way to reproduce:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/153843/216325913-75b606ca-8551-40f6-ad4c-a51c0da0c9df.png">
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/153843/216325970-fa4f4546-d512-40cf-bf74-d5ee998bb94c.png">

```go
conn := driver.NewBasicAuthConnector(ServerName+":443", UserName, Password)
conn.SetTLSConfig(&tls.Config{ServerName: ServerName})
db := sql.OpenDB(conn)
defer db.Close()
rows, err := db.Query(`
   -- my comment
   SELECT * FROM DUMMY`)
require.Nil(t, err)
require.NotNil(t, rows)
```

**Comment by stfnmllr** [comment]
The SQL statement is send 'as-is' to the HANA backend, which does mean, that HANA backend does not recognize the statement as valid containing leading comments.
Please double check
https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/209f5020751910148fd8fe88aa4d79d9.html#loio209f5020751910148fd8fe88aa4d79d9___bsql_introduction_1sql_introduction_comment

>You can add comments to improve the readability and maintainability of your SQL statements. >Comments are delimited in SQL statements as follows:
>Double hyphens "--". Everything after the double hyphen until the end of a line is ignored by the SQL >parser.

>"/*" and "*/". This style of commenting is used to place comments on multiple lines. All text between >the opening "/*" and closing "*/" is ignored by the SQL parser.

It clearly states that everything after double hyphen would be ignored, so in consequence no statement is send to the backend which is answered by the error you do get for the corresponding test.

**Comment by stfnmllr** [comment]
Yes, you are right - it says everything until the end of a line.
I did some more testing and was able to reproduce on go-hdb v0 version. With v1 this issue was already fixed and as Go 1.20 is available since yesterday, go-hdb v1.0.0 is going to be released within the next days - in the meanwhile you might use the latest release candidate.

**Comment by stfnmllr** [comment]
You would find the release candidate version as branch - the current is
https://github.com/SAP/go-hdb/tree/v1.0.0-rc9
Relevant changes can be found here
https://github.com/SAP/go-hdb/blob/main/VERSION1.0.md
and 1.0 is going to support go 1.19 + 1.20 (same like the Go team does support the current and one maintenance release)

**Comment by stfnmllr** [comment]
Yes, in the meanwhile the new v1 version is published 
https://github.com/SAP/go-hdb/tree/main
and the former release candidates are no longer maintained
