### ISSUE TITLE
protocol error: invalid number of lob parameter ids 1

### ISSUE THREAD

**Issue by jeovax** [SAP/go-hdb#106]
I'm trying to insert bulk in Json Document in Hana Cloud like the [Example (BulkInsert)](https://pkg.go.dev/github.com/SAP/go-hdb/driver#example-package-BulkInsert) via 'extended' argument list.

`stmt, err := db.PrepareContext(context.Background(), "INSERT INTO collection VALUES (?);")`

However, in the middle of the inserts I got a fatal panic in the line showed bellow:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/52725130/217231540-e7a3fd05-bede-4cc5-9091-7fa53d51bafb.png">

The panic is because the return variable 'r' is nil. The 'err' before the panic is "protocol error: invalid number of lob parameter ids 1".

**Comment by stfnmllr** [comment]
Ok, thanks a lot for the detailed description of the issue!
For the 'panic' I am going to provide a correction, but for the 
"invalid number of lob parameter ids 1"
issue I would need an example to reproduce the error. Would you be able to provide that?

**Comment by stfnmllr** [comment]
The 'panic' issue should be fixed with https://github.com/SAP/go-hdb/releases/tag/v1.0.4.

**Comment by jeovax** [comment]
Thanks a lot

**Comment by stfnmllr** [comment]
https://github.com/SAP/go-hdb/releases/tag/v1.0.5 should fix the protocol error: invalid number of lob parameter ids 1
