### ISSUE TITLE
Unable to open database connection due to DSN parsing error

### ISSUE THREAD

**Issue by svea-vip** [SAP/go-hdb#116]
If the password contains the # character, the DSN cannot parse because the DSN is truncated by #

u, frag, _ := strings.Cut(rawURL, "#")

**Comment by stfnmllr** [comment]
Yes, the DSN needs to be a well-formed URL string - you might 'escape' the character or use URL unicode syntax instead (see following example):

```
dsn := &url.URL{
	Scheme: "hdb",
	User:   url.UserPassword("MyUser", "MyPassword#"),
	Host:   "localhost:50000",
}
fmt.Println(dsn.String())
```
output:  hdb://MyUser:MyPassword%23@localhost:50000

As an alternative to the DSN you might also use one of the New* methods of
https://pkg.go.dev/github.com/SAP/go-hdb/driver#Connector
instead.
