### ISSUE TITLE
Golang version check fails for some tags

### ISSUE THREAD

**Issue by rabdill** [SAP/go-hdb#16]
Encountered this when the go-hdb was pulled in as a subdependency and started panicking during our app's testing when we upgraded from 0.9.2 to 0.9.4. In short, it looks like the [Go version check added to driver/runtime.go](https://github.com/SAP/go-hdb/blob/6cd71148fb6bfa268ccaa545cf4a3b12f1f5380d/driver/runtime.go#L39) expects the releases of Golang to use semantic versioning, when [they don't](https://github.com/golang/go/releases). It's checking to make sure there are three parts—major, minor and patch—but for people running the Aug. 24 release (`c8aec40`), called only `"go1.9"`, this check fails. I'm assuming similar behavior would pop up with other releases such as `go1.9beta2`.

**Comment by d024441** [comment]
fixed with release 0.9.5
