### ISSUE TITLE
RowsAffected and LastInsertId always 0

### ISSUE THREAD

**Issue by tc-turner** [SAP/go-hdb#17]
When using this driver I am unable to get a proper value for RowsAffected or LastInsertId

##RowsAffected

```
> SET SCHEMA MITCHELL;
Affected Rows 0
Last Insert ID: 0

> INSERT INTO TESTING VALUES ('moose2');
Affected Rows 0
Last Insert ID: 0

> INSERT INTO TESTING VALUES ('moose2ddd');
Affected Rows 0
Last Insert ID: 0

> select * from testing;
+-----------+
|    DAA    |
+-----------+
|     googl |
|     moose |
|    moose2 |
|    moose2 |
|    moose2 |
| moose2ddd |
+-----------+

```

## LastInsertId
```
> CREATE COLUMN TABLE T2 (ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,  NAME VARCHAR(10), PRIMARY KEY (ID));
Affected Rows 0
Last Insert ID: 0
> insert into "MITCHELL"."T2" ("NAME") values('K')
>>> ;
Affected Rows 0
Last Insert ID: 0
```

Are these features implemented?

**Comment by d024441** [comment]
LastInsertId() is not supported by the used HANA protocol but RowsAffected() should work - we are going to double-check

**Comment by d024441** [comment]
Tested RowsAffected() with insert and update and it works (test will be part of the next version). Please share the Go source code example for which you had the issue

**Comment by d024441** [comment]
Didn't hear back, so closing the issue
