### ISSUE TITLE
Panic when calling procedure

### ISSUE THREAD

**Issue by arthurpaimarnold** [SAP/go-hdb#20]
When trying to execute
```sql
CALL proc.myProc(?);
```
we get an `invalid memory address or nil pointer dereference` error.

This seems to be related to the use of the question mark, so maybe the driver is interpreting it as a placeholder in a prepared statement? If so, is it possible to escape it?

**Comment by d024441** [comment]
Yes, the ? is interpreted as place-holder for a in, in-out or out variable of the stored procedure. For what does the ? stand in your example? Can you please share the definition of the stored procedure and the go code calling it?

**Comment by arthurpaimarnold** [comment]
@d024441, according to the [HANA Help Page](https://help.sap.com/viewer/de2486ee947e43e684d39702027f8a94/2.0.01/en-US/729281f732c14860902bcbc5c9cbf6f1.html):

> The actual value passed for tabular OUT parameters must be`?`.

and

> When you pass '?' to the output parameters, temporary tables holding the result sets will be generated. These tables will be dropped automatically once the database session is closed.

Without the question mark, how else could I invoke a procedure to simply get its result (as opposed to calling from within another procedure where the result could be stored in a local variable)?

Thanks!

**Comment by d024441** [comment]
Hi @arthurpaimarnold,

>>Without the question mark, how else could I invoke a procedure to simply get its result (as opposed >>to calling from within another procedure where the result could be stored in a local variable)?

Yes, sure. Please check the example code - maybe this will help:
[](https://godoc.org/github.com/SAP/go-hdb/driver#example-package--CallSimpleOut)
[](https://godoc.org/github.com/SAP/go-hdb/driver#ex-package--CallTableOut)

If not - to reproduce the issue, we need
- the definition (header) of the stored procedure and
- the go code 'calling' the stored procedure

**Comment by arthurpaimarnold** [comment]
@d024441 the examples you provided solved the issue. Thank you very much!
