### ISSUE TITLE
build fails on s390x: "undefined: archEndian"

### ISSUE THREAD

**Issue by logic** [SAP/go-hdb#23]
Builds of 0.12.1 fail on s390x because `archEndian` is only defined in `internal/protocol/littleendian.go` rather than defined in a package everything pulls in and set via `init()` in `littleendian.go`. Build failure is here:

https://kojipkgs.fedoraproject.org//work/tasks/7285/27867285/build.log

If I get a chance later tonight or tomorrow, I'll send a PR, but the fix is pretty straightforward.

**Comment by d024441** [comment]
Hi,
limiting the support to 'known architectures' is intended as endianness matters. We are going to double check and provide a solution asap.
Best regards

**Comment by logic** [comment]
No worries, I'll hold off on submitting a PR then.

I've updated the Fedora package that I maintain of this to exclude s390x for now, and filed a bug about it against Fedora's bugtracker just so we can keep track of it: https://bugzilla.redhat.com/show_bug.cgi?id=1595083

**Comment by d024441** [comment]
big-endian tested ok with qemu debian s390x - release v0.13.1
