### ISSUE TITLE
SAP HANA trust not implemented

### ISSUE THREAD

**Issue by JonathanSilvaMartinsCAN** [SAP/go-hdb#25]
I'm using this driver to connect to HANA. I want to be able to pass the application ID of my program to HANA on the connection string. Example: "hbd://user:password@endpoint:port?SESSIONVARIABLE:APPLICATION=my_app_id"

I know this is possible in the cgo driver that comes with the HANA client, however changing from this to the cgo driver in our project would create several complications. 

Are there any plans to add this functionality?

**Comment by d024441** [comment]
>>> Are there any plans to add this functionality?
will be added to the driver.Connector with the next version (not as part of the data source name)

**Comment by d024441** [comment]
- Added SessionVariables to driver.Connector (version v0.14.0)
- usage: see TestSessionVariables in driver/connector_test.go
Best regards
