### ISSUE TITLE
Cannot connect to HANA in SCP

### ISSUE THREAD

**Issue by rasmk** [SAP/go-hdb#26]
When trying to connect to the HANA DB in SAP Cloud Platform, I get the following message: `SQL Error 4321 - only secure connections are allowed`. I have not found any security-related options though. Is this not supported? Do I need to use the other Go HANA driver instead?

I am trying to connect to an HDI schema in SAP Cloud Foundry if it matters.
The database itself is available. I can connect to it with Java/JDBC without any problems. I get the above message only when trying to use this driver.

**Comment by rasmk** [comment]
Found it. `TLSServerName` query parameter seems to do the job. Not quite sure what it does, but I got some query results.
Some documentation may be helpful.

**Comment by d024441** [comment]
In general you might refer to the HANA TLS configuration documentation.
For this driver please see
https://godoc.org/github.com/SAP/go-hdb/driver
especially the TLS connection examples
https://github.com/SAP/go-hdb/blob/master/driver/dsn.go#L64
and TLS configuration provided by the Connector for extended configuration capabilities
https://github.com/SAP/go-hdb/blob/master/driver/connector.go#L252

**Comment by rasmk** [comment]
@d024441, thanks for the comment.
Still, I have not found any decent explanation of the parameter.

Best found is constant definition. But still not much light. I feel really lucky I tried it and it worked for me.
```
DSNTLSServerName         = "TLSServerName"         // ServerName to verify the hostname.
```

Honestly, I would expect the information, how to connect to HANA in SCP in README.md. After all, SCP is a beloved baby of SAP, isn't it?

**Comment by Schalex1998** [comment]
Why do I have to set "TLSServerName" even though I set "TLSInsecureSkipVerify"? If I do not set TLSServerName I get "driver: bad connection". Seems like a bug to me?

**Comment by stfnmllr** [comment]
Might depend on the server configuration - if validation is not requested a TLS connection can be established by using TLSInsecureSkipVerify only:
Just did a test with the latest driver version:

```
export GOHDBDSN="hdb://MyUser:MyPassword@xxxx.emea.global.corp.sap:33317"
go test -v
SQL Error 4321 - only secure connections are allowed
exit status 1
FAIL	github.com/SAP/go-hdb/driver	0.233s
export GOHDBDSN="hdb://MyUser:MyPassword@xxxx.emea.global.corp.sap:33317?TLSInsecureSkipVerify"
go test -v
dbtest.go:86: created schema goHdbTest_d35pKs2d6cHKn7GX
=== RUN   TestColumnType
=== RUN   TestColumnType/dfv_1
...
```
