### ISSUE TITLE
coltypes[i].DatabaseTypeName() of BOOLEAN Datatype is TINYINT

### ISSUE THREAD

**Issue by aashakabragithub** [SAP/go-hdb#27]
I created a table in SAP HANA DB with both Boolean and Tinyint datatypes, on retrieving DatabaseTypeName using "coltypes[i].DatabaseTypeName()" , I am getting TINYINT for field that is of Boolean datatype.

Is this a defect? I have to process values of fields based on datatype. I am not able to differentiate between tinyint field and boolean field.

**Comment by aashakabragithub** [comment]
Can anyone please share any thoughts on this?

**Comment by d024441** [comment]
This driver implementation is based on SAP HANA SQL command network protocol. The column meta data provided is returning Tinyint for Boolean fields (most probably as boolean fields are implemented technically as tinyints).
Please see 'var testColumnTypeData' in 'columntype_test.go' for reference.
