### ISSUE TITLE
issue with decimal-unsupported Scan, storing driver.Value type []uint8 into type *main.Decimal

### ISSUE THREAD

**Issue by chrislinan** [SAP/go-hdb#28]
Hi, dear

I meet a trouble when I read decimal data from HANA.
I follow this document( https://godoc.org/github.com/SAP/go-hdb/driver#example-Decimal )
Here is a segment of code show us how to read decimal data from HANA : 
```
var out Decimal // Declare scan variable.

if err := db.QueryRow(fmt.Sprintf("select * from %s.%s", TestSchema, tableName)).Scan(&out); err != nil {
    log.Fatal(err)
}

fmt.Printf("Decimal value: %s", (*big.Rat)(&out).String()) // Cast scan variable to *big.Rat to use *big.Rat methods.
```
But I meet a trouble when I  read decimal data as this way.  When I run my code, the error is :
`Scan error on column index 3, name "O_TOTALPRICE": unsupported Scan, storing driver.Value type []uint8 into type *main.Decimal`  
I think that means there is a mismatch of data type.
Here is my code : 
```

	tableRows, err := db.Query(tableQuery)
	if err != nil {
		log.Fatal(err)
	}
	defer tableRows.Close()

	for tableRows.Next() {
		order := orders{}

		err := tableRows.Scan(&order.o_orderkey, &order.o_custkey, &order.o_orderstatus,
			&order.o_totalprice, &order.o_orderdate, &order.o_orderpriority,
			&order.o_clerk, &order.o_shippriority, &order.o_comment)

		if err != nil {
			log.Fatal(err)
		}

		fmt.Println(order)

	}
```

Who can help on this? Thanks a lot.

**Comment by d024441** [comment]
As the error says
'Scan error on column index 3, name "O_TOTALPRICE": unsupported Scan, storing driver.Value type []uint8 into type *main.Decimal'
*main.Decimal type is used to store the decimal. It should be driver.Decimal. So,
- can you please share the definition of main.Decimal and
- can you please share the definition of 'orders'
for any further investigation of the issue?

**Comment by chrislinan** [comment]
Hi, dear
Here is the definition of  main.Decimal and orders:
```
type Decimal big.Rat

type orders struct {
	o_orderkey      int64
	o_custkey       int64
	o_orderstatus   string
	o_totalprice    Decimal
	o_orderdate     string
	o_orderpriority string
	o_clerk         string
	o_shippriority  int64
	o_comment       string
}
```
Thanks a lot.

**Comment by d024441** [comment]
Hi,
the definition should like like follows:

```
// type Decimal big.Rat // not needed and big.Rat will not work - this is the root cause for the error

type orders struct {
	o_orderkey      int64
	o_custkey       int64
	o_orderstatus   string
       // you need to use the driver.Decimal type for doing the db - go conversion magic
	o_totalprice    driver.Decimal // <-- change type
	o_orderdate     string
	o_orderpriority string
	o_clerk         string
	o_shippriority  int64
	o_comment       string
}

```
Best regards

**Comment by chrislinan** [comment]
Hi, dear
driver.Decimal works for me. Thanks a lot.
Best regards!
