### ISSUE TITLE
Scan does not appear to recognize Decimal type

### ISSUE THREAD

**Issue by sdicker8** [SAP/go-hdb#3]
I am attempting to select data and write it to a csv file. Handling of most types works fine but handling of decimal types does not appear to be trivial.
        ...
        n := len(cols)
        vals := make([]interface{}, n)
        dest := make([]interface{}, n)
        for i := 0; i < n; i++ {
                dest[i] = &vals[i]
        }
        for rows.Next() {
                err = rows.Scan(dest...)
                check(err, w)
                for i, v := range vals {
                        switch v := v.(type) {
                        ...
                        }
                }
        }
In code like the above decimal types are coming through as []byte.

Even trying to convert this representation to  a string that I can write has proven elusive.

Am I doing something wrong?

**Comment by d024441** [comment]
Hi,
for decimals please use type Decimal (or NullDecimal respectively). Decimal is a Go big.Rat type (which provides you with methods to convert it to a string, etc.) extended by Scan and Value methods to use it in conjunction with the Go SQL interface.
Please see
- https://godoc.org/github.com/SAP/go-hdb/driver#Decimal for documentation and
- https://github.com/SAP/go-hdb/blob/master/driver/datatype_test.go for usage.
