### ISSUE TITLE
float returned from query incorrectly

### ISSUE THREAD

**Issue by jdezego** [SAP/go-hdb#34]
I have this query:

`SELECT m_disks.used_size / m_disks.total_size * 100  AS DISK_UTILIZATION`

The data that gets returned form HANA looks like this:

`"DISK_UTILIZATION": "7q\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u000080"`

I can work around this by using a `CAST AS INT` in my SQL query, but it seems this might be an issue with the driver.

**Comment by d024441** [comment]
Can you please share a source code example (test) to reproduce the issue?
Thanks an best regards

**Comment by jdezego** [comment]
If you want to actually test this you'll need a running instance of HANA:

```
package main

import (
	"bytes"
	"compress/gzip"
	"database/sql"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"

	_ "github.com/SAP/go-hdb/driver"
)

//structure to hold JSON data
type insightsEvent struct {
	EventType string `json:"eventType"`
	DiskUsage string `json:"diskUsage"`
}

func main() {

	//initialize event object and set EventType
	var event insightsEvent
	event.EventType = "ServiceCheck"

	dsn := "hdb://USERNAME:PASSWORD@HOST:PORT"
	db, err := sql.Open("hdb", dsn)
	defer db.Close()

	if err != nil {
		fmt.Println("Connection failed")
	}

	q := "SELECT m_disks.used_size / m_disks.total_size * 100 FROM sys.m_disks"

	//fill remaining event fields with data returned from query
	err = db.QueryRow(q).Scan(&event.DiskUsage)

	if err != nil {
		fmt.Println(err)
	}

	//convert event to json
	e, err := json.Marshal(event)
	if err != nil {
		fmt.Println(err)
		return
	}

	stringer := string(e)
	fmt.Println(stringer)
```

This is what gets printed:

`{"eventType":"ServiceCheck","diskUsage":"4q\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u000080"}
`

**Comment by d024441** [comment]
please use the expected go type (e.g. float) for scan field event.DiskUsage - with the current string type the result is the string representation of the underlying 'raw' value provided by the hdb interface
