### ISSUE TITLE
Problem to connect SSL on Hana DB SAP - SQL Error 4321 - only secure connections are allowed

### ISSUE THREAD

**Issue by pedrualves** [SAP/go-hdb#35]
Hi, following the link [SAP - Go (golang) Support](https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.02/en-US/8d61ae225ae44b0bab2fb2285009f68d.html) a made the code below:
```golang
package main

import (
	"database/sql"
	_ "github.com/SAP/go-hdb/driver"
	"log"
)

const (
	driverName = "hdb"
	hdbDsn     = "hdb://user:password@hostname:port"
)

func main() {

	db, err := sql.Open(driverName, hdbDsn)

	if err != nil {
		log.Print("error on sql open => " ,err)
	}

	err = db.Ping()

	if err != nil {
		log.Print("error on db.Ping() => " ,err)
	}

}

```

but I have the following problem:

```terminal
2019/11/04 14:59:24 error on db.Ping() => SQL Error 4321 - only secure connections are allowed
```
I, tried too this:

```golang
hdbDsn     = "hdb://user:password@hostname:port?encrypt=true"
```
but is not possible connect to Hana database.

Someone could help me?

Att,

**Comment by navossoc** [comment]
> The following table lists security properties (property names are **case sensitive**) that can be used with Go.

It should be:
`ENCRYPT=TRUE` or `ENCRYPT=true`

The documentation didn't mention if the value is case sensitive too.

**Comment by pedrualves** [comment]
Hi @navossoc, thanks for reply.

I also tried this:
```golang
hdbDsn     = "hdb://user:password@hostname:port?ENCRYPT=TRUE"
```

but dont works =/

**Comment by pedrualves** [comment]
Okay, after a lot of tests I found this palliative solution:

```golang
package main

import (
    "crypto/tls"
    "database/sql"
    "github.com/SAP/go-hdb/driver"
    _ "github.com/SAP/go-hdb/driver"
    "log"
)

const (
    HOST     = "host"
    PORT     = ":port"
    USERNAME = "user"
    PASSWORD = "password"
)

func main() {
    c := driver.NewBasicAuthConnector(
        HOST+PORT,
        USERNAME,
        PASSWORD)

    tlsConfig := tls.Config{
        InsecureSkipVerify: false,
        ServerName:         HOST,
    }

    c.SetTLSConfig(&tlsConfig)

    db := sql.OpenDB(c)

    var id int
    var name string
    res := db.QueryRow("SELECT * FROM SCHEMA.TABLE LIMIT 1")

    res.Scan(&id, &name)

    log.Println("res ", id, name)

}
```

**Comment by d024441** [comment]
Please see Driver Doc (DSN) for examples on how to establish a TLS connection:

Examples TLS connection:

"hdb://myuser:mypassword@localhost:39013?TLSRootCAFile=trust.pem"
"hdb://myuser:mypassword@localhost:39013?TLSRootCAFile=trust.pem&TLSServerName=hostname"
"hdb://myuser:mypassword@localhost:39013?TLSInsecureSkipVerify"
