### ISSUE TITLE
Column type returned not matched for SECONDDATE

### ISSUE THREAD

**Issue by xhit** [SAP/go-hdb#36]
When I print the columns type of SECONDDATE column in a query, returned type is TIMESTAMP.

Example query:

```sql
select CURRENT_DATE "date1",CURRENT_TIME "date2", CURRENT_TIMESTAMP "date3",CAST (CURRENT_TIMESTAMP AS SECONDDATE) "date4" from DUMMY
```

I think is necessary to return types without generalize to know and do integrations.

**Comment by stfnmllr** [comment]
The returned column type is client data format version specific. The return value is correct for current used data format version 1.
From driver version >= 0.14.5 client data format version 4 is going to be the default value, which is going to fix the described issue.
Please see columntype_test.go for details and please have a little more patience until the next driver is going to be released.
