### ISSUE TITLE
MDC Support.

### ISSUE THREAD

**Issue by gentlemanfox** [SAP/go-hdb#4]
Hi, 

I can't find anywhere in the documentation any information about how to connect to tenant databases.  I'm guessing this can be done with a DSN option but I don't know how.

Thanks in advance.

**Comment by d024441** [comment]
Hi,

yes, you should be able to connect to a tenant database by altering the port number in the DSN string

`hdb://<username>:<password>@<host address>:<port number>`

The default for single db instances is 3xx15, where xx is the instance number.

In tenant database setup each tenant has an own SQL port, with a default configuration of

Port 3xx41 connects to the 1st tenant database SQL port
Port 3xx44 connects to the 2nd tenant database SQL port
Port 3xx47 connects to the 2nd tenant database SQL port
...
