### ISSUE TITLE
Do not return password in error messages

### ISSUE THREAD

**Issue by nbys** [SAP/go-hdb#46]
I noticed that if wrong Dsn is provided (e.g. new line character inside password string, eg `passw0rd\n`) then error message will be returned. This message would contain user and password in a plain text. 

https://github.com/SAP/go-hdb/blob/81ab05326d3cc6dab3f42eb6e1cfdab8c92dad63/driver/connector.go#L70

**Comment by stfnmllr** [comment]
Thanks - will be changed in the next release which should be expected within the next days.
