### ISSUE TITLE
ALPHANUM always returns the column length in index 0

### ISSUE THREAD

**Issue by xhit** [SAP/go-hdb#48]
Using v0.99.1, selecting a column `ALPHANUM` always returns the column length in index 0.

Example:

If column value is `a` with length `1` is returned `[1 97]`

If column value is `a` with length `115` is returned `[115 97]`

I don't know if a bug or the expected behavior, if second, there will be documented.

**Comment by stfnmllr** [comment]
yes - will investigate and fix asap

**Comment by stfnmllr** [comment]
should be fixed with release 0.99.2
