### ISSUE TITLE
Does DSN support instance numbers and multiple container specified tenant databases?

### ISSUE THREAD

**Issue by revolveyao** [SAP/go-hdb#49]
The hana studio connection requires an instance number and a tenant database name for multiple containers. DSN query parameters do not appear to be supported.

**Comment by stfnmllr** [comment]
DSN does not support instance numbers and tenant database name, but there is a 1:1 relationsship between them and the ip address (host:port).
Please see the first section in [SAP Help Portal](https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.03/en-US/b250e7fef8614ea0a0973d58eb73bda8.html) as reference.

**Comment by scottlepp** [comment]
@stfnmllr can we reopen this?  According [to the docs](https://help.sap.com/docs/SAP_HANA_PLATFORM/0eec0d68141541d1b07893a39944924e/b250e7fef8614ea0a0973d58eb73bda8.html?version=2.0.03#connecting-to-a-database-at-a-specific-port), the preferred approach is to use the database name.

Other teams in the SAP organization are requesting this feature so they don't have to manage ports.  Request from SAP:
```
This is highly important, not just for us but for the all SAP HANA users because HANA born to be a multi-tenant database with multi-instances.
We want to connect against official datasource DNS name and official port, so that in case of a takeover or tenant move, client settings do not have to get updated.
```
They reference this [go client](https://help.sap.com/docs/SAP_HANA_PLATFORM/0eec0d68141541d1b07893a39944924e/8d61ae225ae44b0bab2fb2285009f68d.html) which has the setting.

**Comment by shelldandy** [comment]
hey there, @stfnmllr im writing about this comment you made:

> In case the database name is used, the host port number is the fixed number of the system database:
> 3<instance>13 (SQL)

is there a way of getting this information with the driver? ideally just providing host + database name, otherwise then it seems like the benefits of adding tenant database name are countered by having to add the port anyways since there seem to be many edge cases towards inferring it based on the link provided

https://help.sap.com/docs/SAP_HANA_PLATFORM/78209c1d3a9b41cd8624338e42a12bf6/7a9343c9f2a2436faa3cfdb5ca00c052.html

**Comment by shelldandy** [comment]
I guess my actual question would be: does the port number for tenant instances that is guaranteed to work is:

`3<instance>13`

**Comment by shelldandy** [comment]
Perfect thank you very much for the clarification!
