### ISSUE TITLE
Test failure on 32 bits architecture

### ISSUE THREAD

**Issue by lucaskanashiro** [SAP/go-hdb#57]
In Ubuntu we have been facing a [test failure on armhf](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/armhf/g/golang-github-sap-go-hdb/20200717_140422_0c007@/log.gz) (32 bits):

```
# github.com/SAP/go-hdb/internal/protocol [github.com/SAP/go-hdb/internal/protocol.test]
src/github.com/SAP/go-hdb/internal/protocol/convert_test.go:66:56: constant -2147483649 overflows int
src/github.com/SAP/go-hdb/internal/protocol/convert_test.go:67:56: constant 2147483648 overflows int
FAIL	github.com/SAP/go-hdb/internal/protocol [build failed]
```

The failed test seems to not work on 32 bits architectures. Please, try to make sure the test suite works fine on it as well.

**Comment by stfnmllr** [comment]
Added linux/arm 32-bit support in latest release 0.101.1.
