### ISSUE TITLE
Got error with .Ping():  server version 0.00.000.00 is not supported

### ISSUE THREAD

**Issue by davidlam-at-home** [SAP/go-hdb#58]
Hi hope this is an easy one.
Does this error indicate something i didn't do?

server version 0.00.000.00 is not supported

Thanks.

**Comment by davidlam-winc-com-au** [comment]
I tried the releases backwards, and v0.100.14 doesn't have the problem.

**Comment by stfnmllr** [comment]
Yes, never go-hdb versions do check hdb versions as hdb versions < 2.00.042 are not supported any more. I am wondering why your instance is not reporting its version. Can you please tell me, which hdb version you are using?

**Comment by davidlam-winc-com-au** [comment]
Thanks for the reply.   Someone tells me it's 1.00.122.  It's possible that's not the exact version because we seem to have a few systems, but should be close.

**Comment by stfnmllr** [comment]
With version
https://github.com/SAP/go-hdb/releases/tag/v0.102.0
does support HANA release 1.00.22 again.

**Comment by davidlam-at-home** [comment]
Thanks @stfnmllr that's great news!
