### ISSUE TITLE
Connection killed after ExecContext is done

### ISSUE THREAD

**Issue by nmaslarski** [SAP/go-hdb#66]
Hello colleagues, 

I have the following situation, which I'm not sure is a bug or just me not understanding something, but it started happening with release 0.100.9

We're using the driver via the standard [go sql package](https://golang.org/pkg/database/sql/).
So we have a db client 		                                                `dbClient, err := hana.Connect(connectionConfig)`
We create a prepared statement                                           `insertStmt, err := dbClient.Prepare(insertStmtSQL)`
And we call ExecContext() on the prepared statement.      `_, err = insertStmt.ExecContext(ctx, ...)`

However sometimes the ctx passed to ExecContext is being cancelled.
And we're expecting that only the current ExecContext is being cancelled. And up untill 0.100.9 our expectations were true.
However since 0.100.9 we see  `session.go:295: Kill session 112685822327579` in the logs.
And any further uses of the PreparedStatement (insertStmt in above snipper) and the dbClient object fail with 

```
hdb.protocol 2020/11/13 09:09:32 session.go:138: Connection read error local address x.x.x.x:xxxxx remote address x.x.x.x:xxxxx: read tcp x.x.x.x:xxxxx->x.x.x.x:xxxxx: use of closed network connection
hdb.protocol 2020/11/13 09:09:32 session.go:154: Connection write error local address x.x.x.x:xxxxx remote address x.x.x.x:xxxxx: set tcp 1x.x.x.x:xxxxx: use of closed network connection
```

I traced down the issue to this particular line that's been added in 0.100.9:
https://github.com/SAP/go-hdb/blob/main/driver/connection.go#L384

**Comment by stfnmllr** [comment]
Thanks for reporting the issue!
Please re-try with https://github.com/SAP/go-hdb/releases/tag/v0.102.5.

**Comment by nmaslarski** [comment]
Works!
Thank you for the quick fix.
