### ISSUE TITLE
Concurrent bulk insert issue

### ISSUE THREAD

**Issue by I068888** [SAP/go-hdb#68]
Concurrent bulk inserts for 10 tables based on one connection get the error as below. 
We don't close the connection before the end of the test.

hdb.driver 2021/01/06 18:01:46 connection.go:724: close: INSERT INTO BLKTEST.BSET(MANDT,BUKRS,BELNR,GJAHR,BUZEI) VALUES (?, ?, ?, ?, ?) - not flushed records: 249)
hdb.driver 2021/01/06 18:01:47 connection.go:724: close: INSERT INTO BLKTEST.CKMI1(MANDT,KALNR,BDATJ,POPER,AWTYP,AWREF,AWORG) VALUES (?, ?, ?, ?, ?, ?, ?) - not flushed records: 1)
hdb.driver 2021/01/06 18:01:51 connection.go:724: close: INSERT INTO BLKTEST.USRBF2(MANDT,BNAME,OBJCT,AUTH) VALUES (?, ?, ?, ?) - not flushed records: 1)
hdb.driver 2021/01/06 18:01:51 connection.go:724: close: INSERT INTO BLKTEST.USRBF2(MANDT,BNAME,OBJCT,AUTH) VALUES (?, ?, ?, ?) - not flushed records: 1)
hdb.driver 2021/01/06 18:01:51 connection.go:724: close: INSERT INTO BLKTEST.USRBF2(MANDT,BNAME,OBJCT,AUTH) VALUES (?, ?, ?, ?) - not flushed records: 1)
hdb.driver 2021/01/06 18:01:52 connection.go:724: close: INSERT INTO BLKTEST.BSID(MANDT,BUKRS,KUNNR,UMSKS,UMSKZ,AUGDT,AUGBL,ZUONR,GJAHR,BELNR,BUZEI) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) - not flushed records: 1)
hdb.driver 2021/01/06 18:01:52 connection.go:724: close: INSERT INTO BLKTEST.USRBF2(MANDT,BNAME,OBJCT,AUTH) VALUES (?, ?, ?, ?) - not flushed records: 169)
hdb.driver 2021/01/06 18:01:52 connection.go:724: close: INSERT INTO BLKTEST.USRBF2(MANDT,BNAME,OBJCT,AUTH) VALUES (?, ?, ?, ?) - not flushed records: 249)

**Comment by stfnmllr** [comment]
The 'close' in the protocol is related to the statement, not the connection.
The error indicates, that not all bulk inserted records are 'flushed', so the final flush statement ('stmt.Exec() - exec without parameters) is probably missing.
