### ISSUE TITLE
Is this supported to access sap hana 1.0?

### ISSUE THREAD

**Issue by WangshengHu** [SAP/go-hdb#69]
Hello, I'm using sap hana 1.0 and I need to access it in my golang project. could this driver be used to access hana 1.0? Thanks for your help!

**Comment by stfnmllr** [comment]
Yes, hana 1.0 sps 12 is going to be supported until end of life of hana version 1.0.

**Comment by WangshengHu** [comment]
Thank you very much! One more question, when I used connection string to connect hana, it throws error "url parameter databaseName is not supported". How can I specify the database while connecting to hana? Is there anyway to do that?

**Comment by WangshengHu** [comment]
I see there is a way to specify the dedicated ip and port to connect a tenant database, is there a way to get the ip/port information of a tenant database under the systemdb?

**Comment by stfnmllr** [comment]
- please find some information about connections to db tenants at
https://help.sap.com/viewer/78209c1d3a9b41cd8624338e42a12bf6/2.0.01/en-US/7a9343c9f2a2436faa3cfdb5ca00c052.html
- the tenant port information should be available via select m_services table
- general information about hana ports can be found at
https://help.sap.com/viewer/ports

**Comment by WangshengHu** [comment]
Thank you! You really saved my day!
