### ISSUE TITLE
Parse dsn error: invalid character "{" in host name

### ISSUE THREAD

**Issue by Quantum-Sicarius** [SAP/go-hdb#72]
I am not sure if there is an alternative method to call Open, but when there is a password that contains the `@` symbol the DSN will fail.

Example code
```
db, err := sql.Open("hdb", "hdb://"+user+":"+password+"@"+DBHost+":"+strconv.Itoa(DBPort))
```

Example password:
`"6kOMLTzlxLd@K(!{bLxkD72t(a#@0w2@`

**Comment by Quantum-Sicarius** [comment]
Solved:
```
	dsn := &url.URL{
		Scheme: "hdb",
		User:   url.UserPassword(user,password),
		Host:   DBHost+":"+strconv.Itoa(DBPort),
	}
	return dsn.String()
````

**Comment by stfnmllr** [comment]
@Quantum-Sicarius: you might double check on https://pkg.go.dev/github.com/SAP/go-hdb/driver#NewBasicAuthConnector as well
