### ISSUE TITLE
Implement Value interface for Lob structure

### ISSUE THREAD

**Issue by revolveyao** [SAP/go-hdb#73]
Can you implements the database/sql/Valuer interface for Lob structure?
When I implement the Gorm custom driver, the custom data type needs to implement the Scanner and Valuer interfaces. However, the Lob structure does not implement the Valuer interface, so we hope to add the implementation.

**Comment by revolveyao** [comment]
Can I replace the custom Lob with `sql.RawBytes` ? When compatible with ORM, it is very troublesome.

**Comment by stfnmllr** [comment]
Currently you need to use whether the driver.Lob or driver.NullLob for hdb Lob fields as these types support 'streaming', which should be the right approach to deal with 'large objects'.
The Valuer interface is not provided, as a Lob instance consists only of an io.Reader and io.Writer and cannot read the data twice from the io.Reader nor read the data which was written to the io.Writer.
How is Gorm dealing with 'large objects' of other databases? Which driver.Value is used? How would Gorm support streaming of 'large objects'?

**Comment by revolveyao** [comment]
MySQL data types include blob. [This driver](https://github.com/go-sql-driver/mysql) supports the use of `[]byte` and `sql.RawBytes`. Can we use the design of other databases for reference and expose blob as byte arrays? I think it will be more versatile.
For the introduction of Gorm custom driver, please refer to the [document](https://gorm.io/docs/write_driver.html). I have opened a warehouse to customize the Gorm driver for HDB, but I have encountered some problems. Maybe I'm not very proficient in golang.
I think it's necessary to support ORM tool if you want to make more use of go-hdb.

**Comment by stfnmllr** [comment]
Unfortunately scanning lob fields into byte slices or the like cannot be supported as this would have a huge negative impact on the driver's memory consumption even in the case a driver.Lob field would be used.
The reason for this is that scanning into such kind of fields would mean, that the driver would need to read the entire 'large object' into memory before the scan happens. Let's assume the size of the 'large object' is x bytes.
- scanning into a []byte would allocate 2*x bytes
- scanning into a sql.RawBytes would allocate 1*x bytes
- scanning into a Lob where the writer is for example an io.File or net.Conn (writing Lob data directly to disk or stream oriented network device)  would allocate 1*x bytes  
- scanning into a Lob where the writer would write to memory (e.g. bytes.Buffer) would allocate 2*x bytes

In contrast to what is mentioned above the current implementation makes use of the 'streaming API' of the database, which does mean, that 'large objects' are read in chunks where normally the chunk size s fulfills s << x and is therefore negligible:
- scanning into a Lob where the writer is for example an io.File or net.Conn (writing Lob data directly to disk or stream oriented network device)  would allocate zero bytes
- scanning into a Lob where the writer would write to memory (e.g. bytes.Buffer) would allocate 1*x bytes

Nonetheless, if I am not wrong, the ORM would support 'custom types' implementing driver.Valuer and sql.Scanner. So, I am going to implement driver.Valuer for Lob (sql.Scanner is already implemented). The return value would be *Lob which is kind of a violation in regards of the return value type driver.Value but go-hdb is able to deal with that. This would be comparable to the other go-hdb 'custom type' Decimal which does return a *big.Rat.
As using a []byte for inserting data into a 'large object' does not have any negative effect on memory usage this is going to be supported as well.

The changes will be made available with the next go-hdb release being published within the next days. I am going to close this issue as soon as the new version is available.

**Comment by revolveyao** [comment]
Thank you for your reply. It's true that I take up a lot of memory when I convert a blob to a byte array.

**Comment by revolveyao** [comment]
After I tried to modify the local code, I found a problem. ORM tool usually uses its own null interface when passing in the scan interface, so there will be null pointer exception when calling lob's scan interface.
I feel that it's too hard for HDB to be used in gorm. I wonder if you can help develop gorm's custom hdb driver.

**Comment by stfnmllr** [comment]
Ok, got it. Should be possible to use go-hdb with ORM - we just might need some more iterations.
Would you be able to share your repository for me to check what's happening and / or can you share the error and source code position where the null pointer exception is raised?

**Comment by revolveyao** [comment]
Here is my [gorm warehouse address](https://github.com/revolveyao/hdb). I changed the mysql driver. At present, I only test the value. You can help to modify and improve it.
I tested the message content of the next PI log through the following test code, but an error was reported.
``` go
type BC_MSG_LOG struct {
	MSG_ID             string `gorm:"primaryKey"`
	ACTION_NAME        string
	MSG_BYTES driver.NullLob `gorm:"type:bytes"`
}

func main() {
	newLogger := logger.New(
		log.New(os.Stdout, "\r\n", log.LstdFlags), // io writer
		logger.Config{
			SlowThreshold: time.Second,
			LogLevel:      logger.Info, // Log level
		},
	)

	db, err := gorm.Open(hdb.New(hdb.Config{
		DriverName: "hdb",
		DSN:        "hdb://user:password@ip:port", 
	}), &gorm.Config{
		Logger: newLogger,
		NamingStrategy: schema.NamingStrategy{
			TablePrefix:   "SAPJAVA1.",
			SingularTable: true,
			NoLowerCase:   true,
		},
		DryRun:                                   false,
		PrepareStmt:                              false,
		AllowGlobalUpdate:                        false,
		DisableAutomaticPing:                     false,
		DisableForeignKeyConstraintWhenMigrating: false,
	})
	if err != nil {
		panic(err)
	}
	var msg BC_MSG_LOG
	msg.MSG_BYTES.Lob = driver.NewLob(new(bytes.Buffer), new(bytes.Buffer))
	db.Select([]string{"MSG_ID", "ACTION_NAME", "MSG_BYTES"}).Where("MSG_ID = ?", "00505683-b621-1eeb-a8fb-24069a1521d4").Find(&msg)
	fmt.Println(msg.ACTION_NAME)
}

```

**Comment by stfnmllr** [comment]
Sorry, I would need some time to double check on the code, but

-  why is the type for msg.MSG_BYTES.Lob driver.Lob, whereas in the struct definition driver.NullLob is used?
-  why is  MSG_BYTES annotated with `gorm:"type:bytes"` - shouldn't it be a 'custom type'?

**Comment by revolveyao** [comment]
- Driver.nulllob contains the field Lob. The package used by the driver here is github.com/sap/go-hdb/driver.
- If you do not use `gorm:"type:bytes"`,you will report an error: the value interface is not implemented, but it is implemented in my local code, and I don't know why it is. Maybe I have a problem with my custom data type.
I think you can write your own test code to test if you combine go-hdb with Gorm.

**Comment by stfnmllr** [comment]
I did create a repo with the test you provided:
https://github.com/stfnmllr/gorm-test
DSN needs to be set by environment variable GOHDBDSN.
Executing the test gives the following error:

```
2021/04/28 12:33:38 /home/sm/go/pkg/mod/github.com/revolveyao/hdb@v0.0.0-20210425023326-93f59db21a9d/hdb.go:67
[info] replacing callback `gorm:update` from /home/sm/go/pkg/mod/github.com/revolveyao/hdb@v0.0.0-20210425023326-93f59db21a9d/hdb.go:67

2021/04/28 12:33:39 /home/sm/Development/go/gorm-test/main.go:53 SQL Error 257 - sql syntax error: incorrect syntax near "`": line 1 col 8 (at pos 8)
[1.057ms] [rows:0] SELECT `MSG_ID`,`ACTION_NAME`,`MSG_BYTES` FROM `SAPJAVA1`.`BC_MSG_LOG` WHERE MSG_ID = '00505683-b621-1eeb-a8fb-24069a1521d4'
```
Looks like the 'HANA identifiers' are invalid. HANA uses double quotes ("). Please see go-hdb driver.Identifier for the same.
Can you double check and inform me when a fix is available?

**Comment by revolveyao** [comment]
Sorry, I changed the code locally and forgot to pull. Now it's OK.

**Comment by stfnmllr** [comment]
Ok, it works now - what do I need to do to see the error about the Lob. When I run the test
https://github.com/stfnmllr/gorm-test
it does complete successfully.

**Comment by revolveyao** [comment]
It is possible that the scan method was not called because select did not fetch the value.

**Comment by stfnmllr** [comment]
Yes, you are right - I was not planning to understand the ORM :-)
Anyway, after changing the code the record is found but no error occurs - what should be next?

2021/04/28 14:41:42 /home/sm/go/pkg/mod/github.com/revolveyao/hdb@v0.0.0-20210428104934-d3d638eb226e/hdb.go:67
[info] replacing callback `gorm:update` from /home/sm/go/pkg/mod/github.com/revolveyao/hdb@v0.0.0-20210428104934-d3d638eb226e/hdb.go:67

```
2021/04/28 14:41:42 /home/sm/Development/go/gorm-test/main.go:92
[9.572ms] [rows:1] SELECT "MSG_ID","ACTION_NAME","MSG_BYTES" FROM "SAPJAVA1"."BC_MSG_LOG" WHERE MSG_ID = '00505683-b621-1eeb-a8fb-24069a1521d4'
A1
```

**Comment by revolveyao** [comment]
OK, I'll test it and see what happens.
