### ISSUE TITLE
ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by I068888** [SAP/go-hdb#86]
Would you please help to check the issue? Whether is it relevant to the hdbclient? Should I use the hdbclient on MACOS-Arm?
# SAP/go-hdb/driver
ld: warning: ignoring file /Applications/sap/hdbclient/libdbcapiHDB.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_dbcapi_affected_rows", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_affected_rows in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_affected_rows)
  "_dbcapi_bind_param", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_bind_param in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_bind_param)
  "_dbcapi_client_version", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_client_version in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_client_version)
  "_dbcapi_commit", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_commit in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_commit)
  "_dbcapi_connect2", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_connect2 in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_connect2)
  "_dbcapi_describe_bind_param", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_describe_bind_param in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_describe_bind_param)
  "_dbcapi_disconnect", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_disconnect in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_disconnect)
  "_dbcapi_error", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_error in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_error_length, __cgo_28307e3c234a_Cfunc_dbcapi_error )
  "_dbcapi_error_length", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_error_length in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_error_length)
  "_dbcapi_execute", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_execute in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_execute_direct, __cgo_28307e3c234a_Cfunc_dbcapi_execute )
  "_dbcapi_execute_direct", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_execute_direct in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_execute_direct)
  "_dbcapi_fetch_next", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_fetch_next in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_fetch_next)
  "_dbcapi_free_connection", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_free_connection in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_free_connection)
  "_dbcapi_free_stmt", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_free_stmt in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_free_stmt)
  "_dbcapi_get_bind_param_info", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_get_bind_param_info in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_get_bind_param_info)
  "_dbcapi_get_column", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_get_column in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_get_column_info, __cgo_28307e3c234a_Cfunc_dbcapi_get_column )
  "_dbcapi_get_column_info", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_get_column_info in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_get_column_info)
  "_dbcapi_get_function_code", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_get_function_code in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_get_function_code)
  "_dbcapi_get_next_result", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_get_next_result in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_get_next_result)
  "_dbcapi_init", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_init in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_init)
  "_dbcapi_new_connection", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_new_connection in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_new_connection)
  "_dbcapi_num_cols", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_num_cols in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_num_cols)
  "_dbcapi_prepare", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_prepare in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_prepare)
  "_dbcapi_reset", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_reset in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_reset)
  "_dbcapi_rollback", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_rollback in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_rollback)
  "_dbcapi_set_autocommit", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_set_autocommit in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_set_autocommit)
  "_dbcapi_set_batch_size", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_set_batch_size in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_set_batch_size)
  "_dbcapi_set_connect_property", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_set_connect_property in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_set_connect_property)
  "_dbcapi_set_query_timeout", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_set_query_timeout in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_set_query_timeout)
  "_dbcapi_set_transaction_isolation", referenced from:
      __cgo_28307e3c234a_Cfunc_dbcapi_set_transaction_isolation in _x002.o
     (maybe you meant: __cgo_28307e3c234a_Cfunc_dbcapi_set_transaction_isolation)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by stfnmllr** [comment]
Sorry, but the error provided is not related to this HANA driver implementation. github.com/SAP/go-hdb does not use CGO nor libdbcapiHDB.
