### ISSUE TITLE
Support for `databaseName` query param

### ISSUE THREAD

**Issue by PedroMilheiroSantosDelaware** [SAP/go-hdb#88]
Hello!

I'm trying to use the `databaseName` query param to specify a database 

From the documentation it seems possible:
https://help.sap.com/viewer/f1b440ded6144a54ada97ff95dac7adf/2.12/en-US/dc835a7abc164bc196ce9ada34a5e82f.html

But when I try I get the error  'URL parameter databaseName is not supported'

This is the test I used (using the SAP HANA, express edition  docker container) 
```go
package test

import (
	"database/sql"
	_ "github.com/SAP/go-hdb/driver"
	"testing"
)

func TestSapHanna(t *testing.T) {
	//This works
	connect(t, "hdb://SYSTEM:HXEHana1@:39017")
	//This fails with the error 'URL parameter databaseName is not supported'
	connect(t, "hdb://SYSTEM:HXEHana1@:39017?databaseName=systemdb")
}

func connect(t *testing.T, connectionString string) {
	t.Helper()
	db, err := sql.Open("hdb", connectionString)
	if err != nil {
		t.Fatal(err)
	}
	db.Close()
}
```

versions:
 - go-hdb: v0.106.0
 - SAP HANA, express edition: store/saplabs/hanaexpress:2.00.057.00.20220119.1

**Comment by stfnmllr** [comment]
The documentation you are referring to is related to another implementation. Please refer to the first section of
https://github.com/SAP/go-hdb#readme

The documentation for this driver you would find at
https://pkg.go.dev/github.com/SAP/go-hdb/driver

This driver is not supporting a 'databaseName' parameter as part of the DSN, but for setting a default schema you might use a connector object instead:
https://pkg.go.dev/github.com/SAP/go-hdb/driver#NewConnector or
https://pkg.go.dev/github.com/SAP/go-hdb/driver#Connector.SetDefaultSchema
