### ISSUE TITLE
insert simple binary data?

### ISSUE THREAD

**Issue by akrieg** [SAP/go-hdb#9]
Hello, I am trying to simply add binary data and get an error:

sql: converting argument $2 type: column converter for data [1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6] type [16]uint8 is not implemented

I used the BulkInsert sample and added a second binary field to the test table:

 `CREATE TABLE TEST (TESTCOL1 INT, TESTCOL2 BINARY(16));`

the insert is for testing only:

`	stmt, err := db.Prepare("bulk insert into test values (?,?)") // Prepare bulk query.`
`       	myid := [16]byte {1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6}`
`        if _, err := stmt.Exec(i,myid); err != nil {`

Is there something special to insert binary data?

Thanks!

**Comment by akrieg** [comment]
Hi,
that sounds perfect, thanks!

**Comment by d024441** [comment]
fixed with #11
